### PR TITLE
Add support for 'as' and 'from' in import statement

### PR DESCRIPTION
**Pull request by yanxiyue**
for issue #209

### CODE REVIEW

**Comment by flof** [comment]
That's great! I will give it a try.

**Comment by yanxiyue** [comment]
hi @ebussieres,  could give some response?

**Comment by tx-francesco-figari** [comment]
@mbosecke @ebussieres 
I'm also interested in this, it's would help me share templates between Pebble and Twig. Is there anything we can help with to get this through?

**Comment by cjbrooks12** [comment]
As it appears this repo is dying, I have decied to create and maintain a new fork of Pebble at [JavaEden/Pebble](https://github.com/JavaEden/pebble), and I would love to get this PR merged into the new repo. Please take this PR and open a new one to the `dev` branch of `JavaEden/pebble`.

The future of Pebble has been shaky for a while now, but I refuse to let Pebble die. It is a great project, and I hope to give it same love and care that the original maintainers have as they built Pebble. If you have any questions about the future of Pebble, please reach out on Gitter. Let's keep this community alive, I hope to see you over at the new location!

**New Pebble Home**
- Original announcement of new ownership: https://github.com/PebbleTemplates/pebble/issues/311#issuecomment-379496941
- https://github.com/JavaEden/pebble
- https://bintray.com/javaeden/Eden/Pebble
- https://gitter.im/JavaEden/pebble

**Comment by ebussieres** [comment]
It seems to cause some performance issue. About 10-15% drop in performance

**Comment by yanxiyue** [comment]
ok, I will try the benchmark later.

**Comment by yanxiyue** [comment]
I did the benchmark test in my development environment. 
Compared to the master branch, the results show that there is not much difference in performance. 
The following are my environmental information and test data. 
And I have move the the MacroAttributeProvider branch down. plz take one more try under your environment. @ebussieres 

```java
// env info
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

Intel Xeon E312xx (Sandy Bridge)
Linux 2.6.32-642.1.1.el6.x86_64 #1 SMP Tue May 31 21:57:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux


// results
// benchmarks-0.jar: version 2.2.0
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  13080.610 ± 238.601  ops/s
Pebble.benchmark  thrpt   50  12950.239 ± 531.155  ops/s

// benchmarks-1.jar: origin master
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  11559.832 ± 414.224  ops/s
Pebble.benchmark  thrpt   50  11423.473 ± 343.797  ops/s

// benchmarks-2.jar: Added support for 'as' and 'from' in import statement
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  11231.329 ± 318.845  ops/s
Pebble.benchmark  thrpt   50  11705.103 ± 360.210  ops/s

// benchmarks-3.jar: Move the MacroAttributeProvider branch down.
Benchmark          Mode  Cnt      Score     Error  Units
Pebble.benchmark  thrpt   50  11372.813 ± 458.316  ops/s
Pebble.benchmark  thrpt   50  11421.412 ± 187.204  ops/s
```

**Comment by ebussieres** [comment]
@yanxiyue It seems that some tests are missing here. Cases when there's a name clash with the alias if it's already defined for example. Please add these tests. Except for that, it's clean and i'll merge it when more tests is gonna be added.

Thanks !

**Comment by yanxiyue** [comment]
ok， i will add some test cases in the next days.

**Pull request merged**
