### PR TITLE
Ability to check for presence of variables from EvaluationContext

### PR DESCRIPTION
**Pull request by objectProgrammer**
Currently getVariable returns null for non-present variables, so you can't know if the value is null or if it doesn't exist.
This pull request adds a containsVariable method to fix this.

### CODE REVIEW

**Comment by ebussieres** [comment]
Please add a unit test

**Comment by objectProgrammer** [comment]
@ebussieres Do you know how I can get the EvaluationContext without an extension? Needed for the test.

**Comment by objectProgrammer** [comment]
I really have no idea how to get it. Besides, this just adds 2 methods that aren't even called by the core itself, are tests really needed?

**Comment by objectProgrammer** [comment]
@ebussieres I've looked a lot but there is no way to get EvalutationContext?

**Comment by objectProgrammer** [comment]
Well, as I got no suggestion on how to get it I used reflection. If it's bad then I'm afraid this can't be merged because there is no other way that I know of. And if you don't merge then I don't care so much because I found that you can cast to EvaluationContextImpl and use getScopeChain to check for contains anyways.

**Comment by objectProgrammer** [comment]
I doubt this will get merged.

**Pull request closed without merging**
