### PR TITLE
More comprehensive fix for illegal reflective access under jdk 9+

### PR DESCRIPTION
**Pull request by zimmi**
While looking into #441 I noticed that the same problem occurs for the private `List` implementation returned by `Arrays::asList` (the `size()` method can't be called, see `LogicTest::testListSize`). That's a general problem for unexported / unopened collection types. The fix is to search these well known public classes for members first. This approach also avoids copying potentially large collections.

~Adding `--illegal-access=deny` to unit tests will fail the build for these errors to avoid regressions in the future.~ Doesn't work, see https://github.com/PebbleTemplates/pebble/pull/443#issuecomment-496643233.

### CODE REVIEW

**Comment by ebussieres** [comment]
@zimmi Did you run the performance benchmark to see if there's a difference ? https://github.com/PebbleTemplates/pebble-performance-test

**Comment by zimmi** [comment]
@ebussieres Nope, will do that now.

**Comment by zimmi** [comment]
Running on `openjdk 12.0.1 2019-04-16`

#### master
    Benchmark          Mode  Cnt      Score     Error  Units
    Pebble.benchmark  thrpt   50  24635.207 ± 180.448  ops/s

#### this PR
    Benchmark          Mode  Cnt      Score     Error  Units
    Pebble.benchmark  thrpt   50  24335.089 ± 253.823  ops/s

**Comment by ebussieres** [comment]
Can you update .travis.yml file to test with multiple jdk ?

**Comment by zimmi** [comment]
The failures are because https://github.com/PebbleTemplates/pebble/pull/445 is not yet merged. Do you want me to add those changes in here and delete the other PR?

**Comment by ebussieres** [comment]
Yes please merge the two PR together. 

Thanks

**Comment by zimmi** [comment]
It is done.

**Comment by ebussieres** [comment]
Thanks

**Comment by zimmi** [comment]
Nice, thanks for merging! And thanks to @NatHerencia for the hard work of finding out the root issue!

**Pull request merged**
